@urlDev=http://localhost:8000/api/category/

### Create category
POST {{urlDev}}/
Content-Type: application/json

{
  "name": "Khác ",
  "image": "Khác.png",
  "type": 1
}

### Find all category
GET {{urlDev}}/?type=1
