@urlDev=http://localhost:8000/api/transaction/

### Find all transactions by userId
GET {{urlDev}}/?type=1

### Create transaction
POST   {{urlDev}}/
Content-Type: application/json

{
   "userId": "647dd504387505c72cfcace6",
   "amount": "10000",
   "date": "2023-06-17",
   "categoryId": "64854ac42f10a8382e2be83b",
   "note": "hehehe"
}

### Find transaction by id
GET {{urlDev}}/647e9355cabdea553b31fbe4

### Delete transaction by id
DELETE  {{urlDev}}/647e92ef973fae786c6c661d

### Update transaction by id
PUT {{urlDev}}/647e936937976ba8ad2a070d
Content-Type: application/json

{
   "amount": "210000",
   "date": "05-07-2023",
   "category": "Ăn uống",
   "note": "Ăn hải sản,..."
}

### Chart line
GET {{urlDev}}/chartline?type=week&startdate=2023-06-12&enddate=2023-06-18

### Chart doughnut
GET {{urlDev}}/chartdoughnut?startdate=2023-06-12&enddate=2023-06-18

### Sum total
GET {{urlDev}}/sumtotal


